# Generated by Django 3.1.4 on 2020-12-11 09:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('transaction', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('expiry', models.DateField()),
                ('card_no', models.IntegerField(validators=[django.core.validators.MaxValueValidator(9999999999999999)])),
                ('cvv', models.IntegerField(validators=[django.core.validators.MaxValueValidator(999)])),
            ],
        ),
    ]
