# Generated by Django 3.1.4 on 2020-12-11 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='card_no',
            new_name='number',
        ),
    ]
